/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/book-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the external catalog for books to register. Nothing is stored. */
        get: operations["searchBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's books, newest first. */
        get: operations["listBooks"];
        put?: never;
        /** Register a book for the authenticated user. */
        post: operations["createBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count the authenticated user's books per reading status. */
        get: operations["countBooksByStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the authenticated user's books. */
        get: operations["getBook"];
        /** Replace the editable fields of one of the authenticated user's books. */
        put: operations["updateBook"];
        post?: never;
        /** Delete one of the authenticated user's books. */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record the page the authenticated user has read up to in one of their books. */
        put: operations["updateBookProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. Open to unauthenticated callers. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BookCandidateResponse: {
            /**
             * @description 著者名。複数なら「, 」区切り。不明なら null。
             * @example Martin Fowler
             */
            author?: string;
            /** @description 表紙の画像の URL（https）。無ければ null。 */
            coverUrl?: string;
            /**
             * @description ISBN。13 桁を優先。不明なら null。
             * @example 9784274224546
             */
            isbn?: string;
            /**
             * @description 書名。
             * @example リファクタリング
             */
            title: string;
            /**
             * Format: int32
             * @description 総ページ数。不明なら null。
             * @example 480
             */
            totalPages?: number;
        };
        BookCreateRequest: {
            /**
             * @description 著者名。
             * @example 山田太郎
             */
            author?: string;
            /**
             * @description 表紙の画像の URL。本の検索（GET /api/book-search）の coverUrl をそのまま渡す。
             * @example https://books.google.com/books/content?id=abc&printsec=frontcover&img=1&zoom=1
             */
            coverUrl?: string;
            /**
             * @description ISBN。形式は検証しない。
             * @example 9784123456789
             */
            isbn?: string;
            /**
             * @description 読書状態。未指定なら WANT_TO_READ。
             * @enum {string}
             */
            status?: "WANT_TO_READ" | "READING" | "DONE";
            /**
             * @description 書名。必須。
             * @example エラーハンドリング入門
             */
            title: string;
            /**
             * Format: int32
             * @description 総ページ数。1 以上。
             * @example 320
             */
            totalPages?: number;
        };
        BookListResponse: {
            /** @description 登録日時の新しい順。 */
            items: components["schemas"]["BookResponse"][];
            /**
             * Format: int64
             * @description 同じ絞り込みでの全件数。limit / offset に関係しない。ページ送りに使う。
             * @example 42
             */
            total: number;
        };
        BookProgressUpdateRequest: {
            /**
             * Format: int32
             * @description 今読んでいるページ。0 以上で、総ページ数があればそれ以下。必須。
             * @example 120
             */
            currentPage: number;
        };
        BookResponse: {
            /**
             * @description 著者名。未設定なら null。
             * @example 山田太郎
             */
            author?: string;
            /** @description 表紙の画像の URL。未設定なら null。 */
            coverUrl?: string;
            /**
             * Format: date-time
             * @description 登録日時。
             */
            createdAt: string;
            /**
             * Format: int32
             * @description 現在のページ。既定は 0。
             * @example 0
             */
            currentPage: number;
            /**
             * Format: int64
             * @description 本の ID。
             * @example 1
             */
            id: number;
            /**
             * @description ISBN。未設定なら null。
             * @example 9784123456789
             */
            isbn?: string;
            /** @description 感想。未設定なら null。 */
            note?: string;
            /**
             * Format: int32
             * @description 5 段階評価。未設定なら null。
             * @example 4
             */
            rating?: number;
            /**
             * @description 読書状態。
             * @enum {string}
             */
            status: "WANT_TO_READ" | "READING" | "DONE";
            /**
             * @description 書名。
             * @example エラーハンドリング入門
             */
            title: string;
            /**
             * Format: int32
             * @description 総ページ数。未設定なら null。
             * @example 320
             */
            totalPages?: number;
            /**
             * Format: date-time
             * @description 更新日時。
             */
            updatedAt: string;
        };
        BookSearchResponse: {
            /** @description 見つかった本。関連の高い順。 */
            items: components["schemas"]["BookCandidateResponse"][];
        };
        BookStatusCountsResponse: {
            /**
             * Format: int64
             * @description 読了した本の冊数。
             * @example 10
             */
            done: number;
            /**
             * Format: int64
             * @description 読書中の本の冊数。
             * @example 2
             */
            reading: number;
            /**
             * Format: int64
             * @description 読みたい本の冊数。
             * @example 3
             */
            wantToRead: number;
        };
        BookUpdateRequest: {
            /**
             * @description 著者名。省略すると消える。
             * @example 山田太郎
             */
            author?: string;
            /**
             * @description 表紙の画像の URL。本の検索（GET /api/book-search）の coverUrl をそのまま渡す。省略すると消える。
             * @example https://books.google.com/books/content?id=abc&printsec=frontcover&img=1&zoom=1
             */
            coverUrl?: string;
            /**
             * @description ISBN。省略すると消える。形式は検証しない。
             * @example 9784123456789
             */
            isbn?: string;
            /**
             * @description 読書状態。必須。
             * @enum {string}
             */
            status: "WANT_TO_READ" | "READING" | "DONE";
            /**
             * @description 書名。必須。
             * @example エラーハンドリング入門
             */
            title: string;
            /**
             * Format: int32
             * @description 総ページ数。1 以上。省略すると消える。
             * @example 320
             */
            totalPages?: number;
        };
        HealthResponse: {
            /**
             * @description Always "ok".
             * @example ok
             */
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchBooks: {
        parameters: {
            query?: {
                /** @description 書名・著者・ISBN など。1〜200 文字。 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookSearchResponse"];
                };
            };
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description この読書状態の本だけを返す。省略するとすべて。 */
                status?: "WANT_TO_READ" | "READING" | "DONE";
                /** @description 1 ページの件数。1〜100。 */
                limit?: number;
                /** @description 読み飛ばす件数。0 以上。 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookListResponse"];
                };
            };
        };
    };
    createBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    countBooksByStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookStatusCountsResponse"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    updateBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBookProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookProgressUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
