/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's books, newest first. */
        get: operations["listBooks"];
        put?: never;
        /** Register a book for the authenticated user. */
        post: operations["createBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one book by id. */
        get: operations["getBook"];
        put?: never;
        post?: never;
        /** Delete one of the authenticated user's books. */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. Open to unauthenticated callers. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user's account. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BookCreateRequest: {
            /**
             * @description 著者名。
             * @example 山田太郎
             */
            author?: string;
            /**
             * @description ISBN。形式は検証しない。
             * @example 9784123456789
             */
            isbn?: string;
            /**
             * @description 読書状態。未指定なら WANT_TO_READ。
             * @enum {string}
             */
            status?: "WANT_TO_READ" | "READING" | "DONE";
            /**
             * @description 書名。必須。
             * @example エラーハンドリング入門
             */
            title: string;
            /**
             * Format: int32
             * @description 総ページ数。1 以上。
             * @example 320
             */
            totalPages?: number;
        };
        BookListResponse: {
            /** @description 登録日時の新しい順。 */
            items: components["schemas"]["BookResponse"][];
        };
        BookResponse: {
            /**
             * @description 著者名。未設定なら null。
             * @example 山田太郎
             */
            author?: string;
            /**
             * Format: date-time
             * @description 登録日時。
             */
            createdAt: string;
            /**
             * Format: int32
             * @description 現在のページ。既定は 0。
             * @example 0
             */
            currentPage: number;
            /**
             * Format: int64
             * @description 本の ID。
             * @example 1
             */
            id: number;
            /**
             * @description ISBN。未設定なら null。
             * @example 9784123456789
             */
            isbn?: string;
            /** @description 感想。未設定なら null。 */
            note?: string;
            /**
             * Format: int32
             * @description 5 段階評価。未設定なら null。
             * @example 4
             */
            rating?: number;
            /**
             * @description 読書状態。
             * @enum {string}
             */
            status: "WANT_TO_READ" | "READING" | "DONE";
            /**
             * @description 書名。
             * @example エラーハンドリング入門
             */
            title: string;
            /**
             * Format: int32
             * @description 総ページ数。未設定なら null。
             * @example 320
             */
            totalPages?: number;
            /**
             * Format: date-time
             * @description 更新日時。
             */
            updatedAt: string;
        };
        HealthResponse: {
            /**
             * @description Always "ok".
             * @example ok
             */
            status?: string;
        };
        User: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            id?: number;
            passwordHash?: string;
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBooks: {
        parameters: {
            query?: {
                /** @description 1 ページの件数。1〜100。 */
                limit?: number;
                /** @description 読み飛ばす件数。0 以上。 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookListResponse"];
                };
            };
        };
    };
    createBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
}
